#!/usr/bin/env python3
"""
Create placeholder PDF figures for missing files.
"""

import os
import sys
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as patches

def create_placeholder_pdf(output_path, title="Placeholder Figure"):
    """Create a simple placeholder PDF figure."""
    fig, ax = plt.subplots(1, 1, figsize=(8, 6))
    
    # Create a simple plot
    ax.text(0.5, 0.7, title, fontsize=16, ha='center', va='center', 
            transform=ax.transAxes, weight='bold')
    ax.text(0.5, 0.5, "This figure will be generated by analysis scripts", 
            fontsize=12, ha='center', va='center', transform=ax.transAxes)
    ax.text(0.5, 0.3, f"File: {os.path.basename(output_path)}", 
            fontsize=10, ha='center', va='center', transform=ax.transAxes)
    
    # Add a border
    rect = patches.Rectangle((0.05, 0.05), 0.9, 0.9, 
                           linewidth=2, edgecolor='red', 
                           facecolor='lightgray', alpha=0.3,
                           transform=ax.transAxes)
    ax.add_patch(rect)
    
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.spines['left'].set_visible(False)
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Created placeholder: {output_path}")

def main():
    # Define the missing figures based on checker output
    missing_figures = [
        "tables_figures/final_figures/F_rolling_kappa_rho.pdf",
        "tables_figures/final_figures/F_counterfactual_breadth.pdf", 
        "tables_figures/final_figures/F_holdout_analysis.pdf",
        "tables_figures/final_figures/retail_coverage.pdf",
        "tables_figures/final_figures/F_breadth_qc_coverage.pdf",
        "tables_figures/final_figures/fig_irf_signsplit.pdf",
        "tables_figures/final_figures/fig_irf_delta.pdf",
        "tables_figures/final_figures/F_option_listing_event.pdf",
        "tables_figures/final_figures/irf_grid.pdf",
        "tables_figures/final_figures/irf_forest.pdf",
        "tables_figures/final_figures/F_counterfactual_irf_paths.pdf",
        "tables_figures/final_figures/robustness/bw_irf.png",
        "tables_figures/final_figures/robustness/ibes_rev_irf.png",
        "tables_figures/final_figures/robustness/mpsych_irf.png",
        "tables_figures/final_figures/robustness/pca_cf_irf.png"
    ]
    
    # Change to the LaTeX directory
    latex_dir = Path("../Sentiment_Feedback_in_Equity_Markets__Asymmetries__Retail_Heterogeneity__and_Structural_Calibration__26_")
    os.chdir(latex_dir)
    
    # Create directories if they don't exist
    os.makedirs("tables_figures/final_figures/robustness", exist_ok=True)
    
    # Create placeholder figures
    for fig_path in missing_figures:
        if not os.path.exists(fig_path):
            title = os.path.basename(fig_path).replace('.pdf', '').replace('.png', '')
            create_placeholder_pdf(fig_path, title)
        else:
            print(f"Figure already exists: {fig_path}")

if __name__ == "__main__":
    main()
